export const INIT = '@@INIT';

export const FETCH_REPOS = 'FETCH_REPOS';
export const REPOS_LOADED = 'REPOS_LOADED';
export const COMMITS_LOADED = 'COMMITS_LOADED';
export const CONTRIBUTORS_LOADED = 'CONTRIBUTORS_LOADED';
export const STATISTICS_LOADED = 'STATISTICS_LOADED';
